#!/bin/bash

## Usage: The purpose of this script is to generate a consensus phylogenic tree
## Input: It takes as input a file generated by make_fasta_and_binary_gt_matrix.r (or any fasta file really) and
##        a patient id. For example <patient1>
## Output: Several files are written to the output directory. The .treefile is used as input for
##         plot_MPBoot_consensus_tree.r

MPBoot_exec=/lustre/scratch117/casm/team268/tc16/Programs/mpboot-sse-1.1.0-Linux/bin/mpboot
iterations=1000
MPBoot_dir=$1
output_dir=$2

mkdir -p ${output_dir}

FASTA_FILE=$3
patient=$4

mkdir -p ${output_dir}${patient}

#run MPBoot with a 1000 bootstrap iterations:
${MPBoot_exec} -s ${FASTA_FILE} -bb ${iterations} -pre ${output_dir}${patient}/${patient}
